name: Feature Request
description: Suggest a new feature.
title: "[Feature]: "
labels:
  - enhancement

body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
    validations:
      required: true